apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "k8s001"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "k8s001"
    spec:
      containers:
        - name: "k8s001"
          image: "rdmregistry01.azurecr.io/k8s001"
          ports:
          - containerPort: 80